apiVersion: v1
kind: Service
metadata:
  name: http-server
  namespace: keda  # Ensure this matches the namespace of your deployment
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: http-server
