apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-server-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: http-server
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "30" # Target CPU utilization percentage
