apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-server-scaler
  namespace: keda
spec:
  scaleTargetRef:
    name: http-server
  minReplicaCount: 1
  maxReplicaCount: 100
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "5" # Target CPU utilization percentage
