apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
        image: hashicorp/http-echo
        args:
          - "-text=hello world"
          - "-listen=:8080"
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m" # Requesting 0.1 CPU cores
          limits:
            cpu: "200m" # Limiting to 0.2 CPU cores
