apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: keda
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "while true; do wget -O- http://http-server.keda.svc.cluster.local; done"]
