apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: Base-web

namePrefix:
  kustomize-

nameSuffix:
  -v1

# configMapGenerator:
# - name: webapp-configmap
#   env: config.properties

