apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"  # Requesting 100 millicpu (0.1 CPU)
          limits:
            cpu: "200m"  # Limiting to 200 millicpu (0.2 CPU)
