apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-generator
spec:
  template:
    spec:
      containers:
      - name: k6
        # Use a specific tag like '0.27.1' instead of 'latest' for better reproducibility and compatibility.
        image: grafana/k6:0.27.1
        command: ["k6", "run", "-", "--vus", "100", "--duration", "900s", "--iterations", "1000"]
        stdin: true
        stdinOnce: true
        tty: true
      restartPolicy: Never
  backoffLimit: 4
