apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-server-scaler
  namespace: keda
spec:
  scaleTargetRef:
    name: http-server
  minReplicaCount: 1  # Optional. Default: 0
  maxReplicaCount: 10  # Optional. Specify the maximum number of replicas
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "80"  # Target CPU utilization percentage to scale on
